apiVersion: 1
datasources:
  - name: HealthRiskMySQL
    uid: health-risk-mysql
    type: mysql
    access: proxy
    url: mysql:3306
    database: health_risk_db
    user: root
    secureJsonData:
      password: root
    isDefault: true
